//----------Hardware Definition for the GNC2.0 board----------//

// process memory allocations
#define USB_STACK_SIZE 0x100
#define BUZZER_STACK_SIZE 0x100
#define SPIMGR_STACK_SIZE 0x200
#define RC_RECEIVER_STACK_SIZE 0x100
#define NAVIGATION_STACK_SIZE 0x300

// SERCOM definitions
#define SPI_SERCOM SERCOM3_REGS
#define I2C1_SERCOM SERCOM2_REGS
#define I2C2_SERCOM SERCOM0_REGS
#define I2C3_SERCOM SERCOM5_REGS
#define UART1_SERCOM SERCOM0_REGS
#define UART2_SERCOM SERCOM1_REGS
#define UART3_SERCOM SERCOM4_REGS
#define UART4_SERCOM SERCOM5_REGS

// DMA definitions
#define SPI_DMA_TX_CHANNEL 0
#define SPI_DMA_RX_CHANNEL 1
#define SPI_DMA_TX_TRIGGER SERCOM3_DMAC_ID_TX
#define SPI_DMA_RX_TRIGGER SERCOM3_DMAC_ID_RX
#define SPI_DMA_PRIORITY 1

#define UART1_DMA_TX_CHANNEL 2
#define UART1_DMA_RX_CHANNEL 3
#define UART1_DMA_TX_TRIGGER SERCOM0_DMAC_ID_TX
#define UART1_DMA_RX_TRIGGER SERCOM0_DMAC_ID_RX
#define UART1_DMA_PRIORITY 2

#define UART2_DMA_TX_CHANNEL 4
#define UART2_DMA_RX_CHANNEL 5
#define UART2_DMA_TX_TRIGGER SERCOM1_DMAC_ID_TX
#define UART2_DMA_RX_TRIGGER SERCOM1_DMAC_ID_RX
#define UART2_DMA_PRIORITY 2

#define UART3_DMA_TX_CHANNEL 6
#define UART3_DMA_RX_CHANNEL 7
#define UART3_DMA_TX_TRIGGER SERCOM4_DMAC_ID_TX
#define UART3_DMA_RX_TRIGGER SERCOM4_DMAC_ID_RX
#define UART3_DMA_PRIORITY 2

#define UART4_DMA_TX_CHANNEL 8
#define UART4_DMA_RX_CHANNEL 9
#define UART4_DMA_TX_TRIGGER SERCOM5_DMAC_ID_TX
#define UART4_DMA_RX_TRIGGER SERCOM5_DMAC_ID_RX
#define UART4_DMA_PRIORITY 2

typedef enum {
	SPI_DEVICE_EEPROM,
	SPI_DEVICE_FLASH,
	SPI_DEVICE_IMU,
	SPI_DEVICE_MAGNETOMETER,
	SPI_DEVICE_BAROMETER
} SPI_Device;

// pin definitions
#define SPI_PORT_A PORT_PORTA
#define SPI_PINS_A (PORT_PA22 | PORT_PA23)
#define SPI_PMUX_A PORT_PMUX_C
#define SPI_PORT_B PORT_PORTA
#define SPI_PINS_B PORT_PA20
#define SPI_PMUX_B PORT_PMUX_D
#define SPI_DIPO 2
#define SPI_DOPO 0

#define I2C1_PORT PORT_PORTA
#define I2C1_PINS (PORT_PA12 | PORT_PA13)
#define I2C1_PMUX PORT_PMUX_C

#define I2C2_PORT PORT_PORTA
#define I2C2_PINS (PORT_PA08 | PORT_PA09)
#define I2C2_PMUX PORT_PMUX_C

#define I2C3_PORT PORT_PORTB
#define I2C3_PINS (PORT_PB16 | PORT_PB17)
#define I2C3_PMUX PORT_PMUX_C

#define UART1_PORT PORT_PORTA
#define UART1_PINS (PORT_PA08 | PORT_PA09)
#define UART1_PMUX PORT_PMUX_C
#define UART1_RXPO 1
#define UART1_TXPO 0

#define UART2_PORT PORT_PORTA
#define UART2_PINS (PORT_PA18 | PORT_PA19)
#define UART2_PMUX PORT_PMUX_C
#define UART2_RXPO 3
#define UART2_TXPO 1

#define UART3_PORT PORT_PORTB
#define UART3_PINS (PORT_PB14 | PORT_PB15)
#define UART3_PMUX PORT_PMUX_C
#define UART3_RXPO 3
#define UART3_TXPO 1

#define UART4_PORT PORT_PORTB
#define UART4_PINS (PORT_PB16 | PORT_PB17)
#define UART4_PMUX PORT_PMUX_C
#define UART4_RXPO 1
#define UART4_TXPO 0

#define IMU_SS_PORT PORT_PORTA
#define IMU_SS_PIN PORT_PA27

#define BARO_SS_PORT PORT_PORTA
#define BARO_SS_PIN PORT_PA28

#define EEPROM_SS_PORT PORT_PORTB
#define EEPROM_SS_PIN PORT_PB30

#define FLASH_SS_PORT PORT_PORTB
#define FLASH_SS_PIN PORT_PB31

#define IMU_BUSEN_PORT PORT_PORTA
#define IMU_BUSEN_PIN PORT_PA21

// value definitions
#define SPI_BAUD 2000000
#define UART1_BAUD 4800
#define UART2_BAUD 420000
#define UART3_BAUD 9600
#define UART4_BAUD 4800

#define SPI_EEPROM_SIZE 0x8000
#define SPI_FLASH_SIZE 0x400000
#define SPI_FLASH_DENSITY_CODE 0b00111

// macro definitons
#define IMU_ON_BUS() port_set(IMU_BUSEN_PORT, IMU_BUSEN_PIN)
#define IMU_OFF_BUS() port_clear(IMU_BUSEN_PORT, IMU_BUSEN_PIN)